### ISSUE TITLE
Todo( Generally )

### ISSUE THREAD

**Issue by Poseidonn77** [Poseidonn77/Labour-Compensation#1]
- [ ] Create the core system.
- [ ] Create the App
- [ ] Create a web portal
- [ ] Make this system self sufficient
- [ ] Contemplate making a new Blockchain...
