### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Poseidonn77** [Poseidonn77/Labour-Compensation#2]
- [ ] Build the nessasery classes/functions.
- [ ] Investigate how to implement the exchage flow measuring and execution per time interval.
- [ ] Create an generalized API method allowing integration with several other exchanges simeltaneusly.
